// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnHJU-hwGAjyR6EtImMSAbwmLQ0VuKCRU',
    appId: '1:581441302967:web:a4280066ee1d1c9898f832',
    messagingSenderId: '581441302967',
    projectId: 'cloverproje',
    authDomain: 'cloverproje.firebaseapp.com',
    storageBucket: 'cloverproje.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpgM_nQt64yanKoKwVVxHu5qV5UIU7H3Y',
    appId: '1:581441302967:android:189eae8788adb44298f832',
    messagingSenderId: '581441302967',
    projectId: 'cloverproje',
    storageBucket: 'cloverproje.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCf-uEZFBygf9KM9-ACC-ShscmnJDCgyw',
    appId: '1:581441302967:ios:dc13398c906d87cc98f832',
    messagingSenderId: '581441302967',
    projectId: 'cloverproje',
    storageBucket: 'cloverproje.firebasestorage.app',
    iosBundleId: 'com.example.haribo4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCf-uEZFBygf9KM9-ACC-ShscmnJDCgyw',
    appId: '1:581441302967:ios:dc13398c906d87cc98f832',
    messagingSenderId: '581441302967',
    projectId: 'cloverproje',
    storageBucket: 'cloverproje.firebasestorage.app',
    iosBundleId: 'com.example.haribo4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnHJU-hwGAjyR6EtImMSAbwmLQ0VuKCRU',
    appId: '1:581441302967:web:27c013f73511000f98f832',
    messagingSenderId: '581441302967',
    projectId: 'cloverproje',
    authDomain: 'cloverproje.firebaseapp.com',
    storageBucket: 'cloverproje.firebasestorage.app',
  );
}
